# Source file: ngdist.R
#
# GPL-3 License
#
# Copyright (c) 2024-2026 Victor Ordu

# The creation of a distance city_matrix that contains the distances between State
# captals of Nigeria (in kilometres)
local({
  devtools::load_all()
  
  city_dist <- tibble::tribble(
    ~from,           ~to,              ~km,
    "Abakaliki",     "Abeokuta",       656,
    "Abakaliki",     "Abuja",          477,
    "Abakaliki",     "Ado-Ekiti",      566,
    "Abakaliki",     "Akure",          506,
    "Abakaliki",     "Asaba",          193,
    "Abakaliki",     "Awka",           146,
    "Abakaliki",     "Bauchi",         824,
    "Abakaliki",     "Benin City",     338,
    "Abakaliki",     "Birnin Kebbi",   1294,
    "Abakaliki",     "Calabar",        360,
    "Abakaliki",     "Damaturu",       1103,
    "Abakaliki",     "Dutse",          994,
    "Abakaliki",     "Enugu",          84,
    "Abakaliki",     "Gombe",          974,
    "Abakaliki",     "Gusau",          1116,
    "Abakaliki",     "Ibadan",         642,
    "Abakaliki",     "Lagos",          500,
    "Abakaliki",     "Ilorin",         737,
    "Abakaliki",     "Jalingo",        626,
    "Abakaliki",     "Jos",            692,
    "Abakaliki",     "Kaduna",         856,
    "Abakaliki",     "Kano",           1157,
    "Abakaliki",     "Katsina",        1205,
    "Abakaliki",     "Lafia",          388,
    "Abakaliki",     "Lokoja",         476,
    "Abakaliki",     "Maiduguri",      1285,
    "Abakaliki",     "Makurdi",        256,
    "Abakaliki",     "Minna",          662,
    "Abakaliki",     "Osogbo",         516,
    "Abakaliki",     "Owerri",         230,
    "Abakaliki",     "Port Harcourt",  313,
    "Abakaliki",     "Sokoto",         1358,
    "Abakaliki",     "Umuahia",        202,
    "Abakaliki",     "Uyo",            273,
    "Abakaliki",     "Yenagoa",        346,
    "Abakaliki",     "Yola",           854,
    
    "Abeokuta",      "Abuja",          722,
    "Abeokuta",      "Ado-Ekiti",      340,
    "Abeokuta",      "Akure",          200,
    "Abeokuta",      "Asaba",          460,
    "Abeokuta",      "Awka",           444,
    "Abeokuta",      "Bauchi",         1143,
    "Abeokuta",      "Benin City",     314,
    "Abeokuta",      "Birnin Kebbi",   756,
    "Abeokuta",      "Calabar",        761,
    "Abeokuta",      "Damaturu",       1384,
    "Abeokuta",      "Dutse",          1140,
    "Abeokuta",      "Enugu",          572,
    "Abeokuta",      "Gombe",          1304,
    "Abeokuta",      "Gusau",          1110,
    "Abeokuta",      "Ibadan",         75,
    "Abeokuta",      "Lagos",          82,
    "Abeokuta",      "Ilorin",         230,
    "Abeokuta",      "Jalingo",        1312,
    "Abeokuta",      "Jos",            1015,
    "Abeokuta",      "Kaduna",         835,
    "Abeokuta",      "Kano",           1036,
    "Abeokuta",      "Katsina",        1161,
    "Abeokuta",      "Lafia",          502,
    "Abeokuta",      "Lokoja",         520,
    "Abeokuta",      "Maiduguri",      1596,
    "Abeokuta",      "Makurdi",        991,
    "Abeokuta",      "Minna",          663,
    "Abeokuta",      "Osogbo",         167,
    "Abeokuta",      "Owerri",         559,
    "Abeokuta",      "Port Harcourt",  571,
    "Abeokuta",      "Sokoto",         970,
    "Abeokuta",      "Umuahia",        595,
    "Abeokuta",      "Uyo",            691,
    "Abeokuta",      "Yenagoa",        524,
    "Abeokuta",      "Yola",           1560,
    
    "Abuja",         "Ado-Ekiti",      450,
    "Abuja",         "Akure",          420,
    "Abuja",         "Asaba",          404,
    "Abuja",         "Awka",           440,
    "Abuja",         "Bauchi",         419,
    "Abuja",         "Benin City",     493,
    "Abuja",         "Birnin Kebbi",   573,
    "Abuja",         "Calabar",        729,
    "Abuja",         "Damaturu",       957,
    "Abuja",         "Dutse",          512,
    "Abuja",         "Enugu",          393,
    "Abuja",         "Gombe",          606,
    "Abuja",         "Gusau",          490,
    "Abuja",         "Ibadan",         645,
    "Abuja",         "Lagos",          761,
    "Abuja",         "Ilorin",         482,
    "Abuja",         "Jalingo",        691,
    "Abuja",         "Jos",            297,
    "Abuja",         "Kaduna",         186,
    "Abuja",         "Kano",           396,
    "Abuja",         "Katsina",        570,
    "Abuja",         "Lafia",          180,
    "Abuja",         "Lokoja",         193,
    "Abuja",         "Maiduguri",      875,
    "Abuja",         "Makurdi",        220,
    "Abuja",         "Minna",          155,
    "Abuja",         "Osogbo",         428,
    "Abuja",         "Owerri",         533,
    "Abuja",         "Port Harcourt",  616,
    "Abuja",         "Sokoto",         740,
    "Abuja",         "Umuahia",        513,
    "Abuja",         "Uyo",            593,
    "Abuja",         "Yenagoa",        647,
    "Abuja",         "Yola",           704,
    
    "Ado-Ekiti",     "Akure",          60,
    "Ado-Ekiti",     "Asaba",          368,
    "Ado-Ekiti",     "Awka",           412,
    "Ado-Ekiti",     "Bauchi",         945,
    "Ado-Ekiti",     "Benin City",     228,
    "Ado-Ekiti",     "Birnin Kebbi",   684,
    "Ado-Ekiti",     "Calabar",        679,
    "Ado-Ekiti",     "Damaturu",       1207,
    "Ado-Ekiti",     "Dutse",          1130,
    "Ado-Ekiti",     "Enugu",          482,
    "Ado-Ekiti",     "Gombe",          1124,
    "Ado-Ekiti",     "Gusau",          1021,
    "Ado-Ekiti",     "Ibadan",         264,
    "Ado-Ekiti",     "Lagos",          401,
    "Ado-Ekiti",     "Ilorin",         184,
    "Ado-Ekiti",     "Jalingo",        940,
    "Ado-Ekiti",     "Jos",            910,
    "Ado-Ekiti",     "Kaduna",         761,
    "Ado-Ekiti",     "Kano",           1010,
    "Ado-Ekiti",     "Katsina",        1071,
    "Ado-Ekiti",     "Lafia",          640,
    "Ado-Ekiti",     "Lokoja",         296,
    "Ado-Ekiti",     "Maiduguri",      536,
    "Ado-Ekiti",     "Makurdi",        640,
    "Ado-Ekiti",     "Minna",          586,
    "Ado-Ekiti",     "Osogbo",         170,
    "Ado-Ekiti",     "Owerri",         473,
    "Ado-Ekiti",     "Port Harcourt",  584,
    "Ado-Ekiti",     "Sokoto",         994,
    "Ado-Ekiti",     "Umuahia",        510,
    "Ado-Ekiti",     "Uyo",            605,
    "Ado-Ekiti",     "Yenagoa",        130,
    "Ado-Ekiti",     "Yola",           1235,
    
    "Akure",         "Asaba",          310,
    "Akure",         "Awka",           342,
    "Akure",         "Bauchi",         805,
    "Akure",         "Benin City",     168,
    "Akure",         "Birnin Kebbi",   711,
    "Akure",         "Calabar",        619,
    "Akure",         "Damaturu",       1147,
    "Akure",         "Dutse",          1070,
    "Akure",         "Enugu",          422,
    "Akure",         "Gombe",          1268,
    "Akure",         "Gusau",          1057,
    "Akure",         "Ibadan",         204,
    "Akure",         "Lagos",          341,
    "Akure",         "Ilorin",         199,
    "Akure",         "Jalingo",        880,
    "Akure",         "Jos",            682,
    "Akure",         "Kaduna",         749,
    "Akure",         "Kano",           1046,
    "Akure",         "Katsina",        1100,
    "Akure",         "Lafia",          600,
    "Akure",         "Lokoja",         236,
    "Akure",         "Maiduguri",      1279,
    "Akure",         "Makurdi",        580,
    "Akure",         "Minna",          632,
    "Akure",         "Osogbo",         396,
    "Akure",         "Owerri",         97,
    "Akure",         "Port Harcourt",  524,
    "Akure",         "Sokoto",         930,
    "Akure",         "Umuahia",        430,
    "Akure",         "Uyo",            545,
    "Akure",         "Yenagoa",        370,
    "Akure",         "Yola",           1100,
    
    "Asaba",         "Awka",           44,
    "Asaba",         "Bauchi",         824,
    "Asaba",         "Benin City",     133,
    "Asaba",         "Birnin Kebbi",   1027,
    "Asaba",         "Calabar",        297,
    "Asaba",         "Damaturu",       1135,
    "Asaba",         "Dutse",          1000,
    "Asaba",         "Enugu",          100,
    "Asaba",         "Gombe",          979,
    "Asaba",         "Gusau",          1005,
    "Asaba",         "Ibadan",         430,
    "Asaba",         "Lagos",          407,
    "Asaba",         "Ilorin",         507,
    "Asaba",         "Jalingo",        859,
    "Asaba",         "Jos",            692,
    "Asaba",         "Kaduna",         745,
    "Asaba",         "Kano",           1007,
    "Asaba",         "Katsina",        1098,
    "Asaba",         "Lafia",          435,
    "Asaba",         "Lokoja",         362,
    "Asaba",         "Maiduguri",      1200,
    "Asaba",         "Makurdi",        353,
    "Asaba",         "Minna",          673,
    "Asaba",         "Osogbo",         396,
    "Asaba",         "Owerri",         97,
    "Asaba",         "Port Harcourt",  225,
    "Asaba",         "Sokoto",         1232,
    "Asaba",         "Umuahia",        166,
    "Asaba",         "Uyo",            247,
    "Asaba",         "Yenagoa",        213,
    "Asaba",         "Yola",           980,
    
    "Awka",          "Bauchi",         803,
    "Awka",          "Benin City",     166,
    "Awka",          "Birnin Kebbi",   1245,
    "Awka",          "Calabar",        259,
    "Awka",          "Damaturu",       1115,
    "Awka",          "Dutse",          976,
    "Awka",          "Enugu",          62,
    "Awka",          "Gombe",          958,
    "Awka",          "Gusau",          984,
    "Awka",          "Ibadan",         457,
    "Awka",          "Lagos",          494,
    "Awka",          "Ilorin",         528,
    "Awka",          "Jalingo",        815,
    "Awka",          "Jos",            671,
    "Awka",          "Kaduna",         724,
    "Awka",          "Kano",           886,
    "Awka",          "Katsina",        1077,
    "Awka",          "Lafia",          416,
    "Awka",          "Lokoja",         456,
    "Awka",          "Maiduguri",      1245,
    "Awka",          "Makurdi",        332,
    "Awka",          "Minna",          926,
    "Awka",          "Osogbo",         425,
    "Awka",          "Owerri",         141,
    "Awka",          "Port Harcourt",  255,
    "Awka",          "Sokoto",         1211,
    "Awka",          "Umuahia",        126,
    "Awka",          "Uyo",            207,
    "Awka",          "Yenagoa",        257,
    "Awka",          "Yola",           746,
    
    "Bauchi",        "Benin City",     880,
    "Bauchi",        "Birnin Kebbi",   962,
    "Bauchi",        "Calabar",        1002,
    "Bauchi",        "Damaturu",       312,
    "Bauchi",        "Dutse",          316,
    "Bauchi",        "Enugu",          740,
    "Bauchi",        "Gombe",          155,
    "Bauchi",        "Gusau",          670,
    "Bauchi",        "Ibadan",         1080,
    "Bauchi",        "Lagos",          1202,
    "Bauchi",        "Ilorin",         909,
    "Bauchi",        "Jalingo",        410,
    "Bauchi",        "Jos",            130,
    "Bauchi",        "Kaduna",         410,
    "Bauchi",        "Kano",           301,
    "Bauchi",        "Katsina",        518,
    "Bauchi",        "Lafia",          326,
    "Bauchi",        "Lokoja",         601,
    "Bauchi",        "Maiduguri",      462,
    "Bauchi",        "Makurdi",        469,
    "Bauchi",        "Minna",          590,
    "Bauchi",        "Osogbo",         908,
    "Bauchi",        "Owerri",         979,
    "Bauchi",        "Port Harcourt",  970,
    "Bauchi",        "Sokoto",         777,
    "Bauchi",        "Umuahia",        860,
    "Bauchi",        "Uyo",            943,
    "Bauchi",        "Yenagoa",        995,
    "Bauchi",        "Yola",           416,
    
    "Benin City",    "Birnin Kebbi",   882,
    "Benin City",    "Calabar",        490,
    "Benin City",    "Damaturu",       1274,
    "Benin City",    "Dutse",          880,
    "Benin City",    "Enugu",          254,
    "Benin City",    "Gombe",          1044,
    "Benin City",    "Gusau",          1046,
    "Benin City",    "Ibadan",         300,
    "Benin City",    "Lagos",          322,
    "Benin City",    "Ilorin",         399,
    "Benin City",    "Jalingo",        998,
    "Benin City",    "Jos",            756,
    "Benin City",    "Kaduna",         786,
    "Benin City",    "Kano",           1049,
    "Benin City",    "Katsina",        1252,
    "Benin City",    "Lafia",          673,
    "Benin City",    "Lokoja",         287,
    "Benin City",    "Maiduguri",      1353,
    "Benin City",    "Makurdi",        506,
    "Benin City",    "Minna",          608,
    "Benin City",    "Osogbo",         259,
    "Benin City",    "Owerri",         240,
    "Benin City",    "Port Harcourt",  295,
    "Benin City",    "Sokoto",         1020,
    "Benin City",    "Umuahia",        279,
    "Benin City",    "Uyo",            875,
    "Benin City",    "Yenagoa",        210,
    "Benin City",    "Yola",           1107,
    
    "Birnin Kebbi",  "Calabar",        1316,
    "Birnin Kebbi",  "Damaturu",       1101,
    "Birnin Kebbi",  "Dutse",          650,
    "Birnin Kebbi",  "Enugu",          1120,
    "Birnin Kebbi",  "Gombe",          1117,
    "Birnin Kebbi",  "Gusau",          322,
    "Birnin Kebbi",  "Ibadan",         679,
    "Birnin Kebbi",  "Lagos",          826,
    "Birnin Kebbi",  "Ilorin",         520,
    "Birnin Kebbi",  "Jalingo",        1266,
    "Birnin Kebbi",  "Jos",            830,
    "Birnin Kebbi",  "Kaduna",         550,
    "Birnin Kebbi",  "Kano",           651,
    "Birnin Kebbi",  "Katsina",        596,
    "Birnin Kebbi",  "Lafia",          753,
    "Birnin Kebbi",  "Lokoja",         832,
    "Birnin Kebbi",  "Maiduguri",      1404,
    "Birnin Kebbi",  "Makurdi",        898,
    "Birnin Kebbi",  "Minna",          456,
    "Birnin Kebbi",  "Osogbo",         635,
    "Birnin Kebbi",  "Owerri",         1124,
    "Birnin Kebbi",  "Port Harcourt",  1282,
    "Birnin Kebbi",  "Sokoto",         160,
    "Birnin Kebbi",  "Umuahia",        1272,
    "Birnin Kebbi",  "Uyo",            1353,
    "Birnin Kebbi",  "Yenagoa",        1092,
    "Birnin Kebbi",  "Yola",           1400,
    
    "Calabar",       "Damaturu",       988,
    "Calabar",       "Dutse",          1050,
    "Calabar",       "Enugu",          276,
    "Calabar",       "Gombe",          1152,
    "Calabar",       "Gusau",          1309,
    "Calabar",       "Ibadan",         518,
    "Calabar",       "Lagos",          772,
    "Calabar",       "Ilorin",         849,
    "Calabar",       "Jalingo",        624,
    "Calabar",       "Jos",            370,
    "Calabar",       "Kaduna",         1034,
    "Calabar",       "Kano",           1296,
    "Calabar",       "Katsina",        1461,
    "Calabar",       "Lafia",          514,
    "Calabar",       "Lokoja",         579,
    "Calabar",       "Maiduguri",      1465,
    "Calabar",       "Makurdi",        532,
    "Calabar",       "Minna",          860,
    "Calabar",       "Osogbo",         695,
    "Calabar",       "Owerri",         200,
    "Calabar",       "Port Harcourt",  195,
    "Calabar",       "Sokoto",         1535,
    "Calabar",       "Umuahia",        154,
    "Calabar",       "Uyo",            87,
    "Calabar",       "Yenagoa",        300,
    "Calabar",       "Yola",           1132,
    
    "Damaturu",      "Dutse",          286,
    "Damaturu",      "Enugu",          1099,
    "Damaturu",      "Gombe",          256,
    "Damaturu",      "Gusau",          710,
    "Damaturu",      "Ibadan",         1274,
    "Damaturu",      "Lagos",          1421,
    "Damaturu",      "Ilorin",         1292,
    "Damaturu",      "Jalingo",        364,
    "Damaturu",      "Jos",            441,
    "Damaturu",      "Kaduna",         724,
    "Damaturu",      "Kano",           430,
    "Damaturu",      "Katsina",        603,
    "Damaturu",      "Lafia",          640,
    "Damaturu",      "Lokoja",         895,
    "Damaturu",      "Maiduguri",      130,
    "Damaturu",      "Makurdi",        783,
    "Damaturu",      "Minna",          874,
    "Damaturu",      "Osogbo",         1407,
    "Damaturu",      "Owerri",         1273,
    "Damaturu",      "Port Harcourt",  1172,
    "Damaturu",      "Sokoto",         1013,
    "Damaturu",      "Umuahia",        1251,
    "Damaturu",      "Uyo",            1029,
    "Damaturu",      "Yenagoa",        1523,
    "Damaturu",      "Yola",           322,
    
    "Dutse",         "Enugu",          910,
    "Dutse",         "Gombe",          895,
    "Dutse",         "Gusau",          4416,   # note: this looks like a possible typo (4416 km?); check your source
    "Dutse",         "Ibadan",         963,
    "Dutse",         "Lagos",          1110,
    "Dutse",         "Ilorin",         846,
    "Dutse",         "Jalingo",        542,
    "Dutse",         "Jos",            438,
    "Dutse",         "Kaduna",         338,
    "Dutse",         "Kano",           136,
    "Dutse",         "Katsina",        296,
    "Dutse",         "Lafia",          634,
    "Dutse",         "Lokoja",         650,
    "Dutse",         "Maiduguri",      418,
    "Dutse",         "Makurdi",        708,
    "Dutse",         "Minna",          558,
    "Dutse",         "Osogbo",         958,
    "Dutse",         "Owerri",         1076,
    "Dutse",         "Port Harcourt",  1150,
    "Dutse",         "Sokoto",         520,
    "Dutse",         "Umuahia",        1080,
    "Dutse",         "Uyo",            1150,
    "Dutse",         "Yenagoa",        1132,
    "Dutse",         "Yola",           550,
    
    "Enugu",         "Gombe",          890,
    "Enugu",         "Gusau",          1046,
    "Enugu",         "Ibadan",         558,
    "Enugu",         "Lagos",          376,
    "Enugu",         "Ilorin",         553,
    "Enugu",         "Jalingo",        735,
    "Enugu",         "Jos",            608,
    "Enugu",         "Kaduna",         772,
    "Enugu",         "Kano",           1083,
    "Enugu",         "Katsina",        1202,
    "Enugu",         "Lafia",          705,
    "Enugu",         "Lokoja",         398,
    "Enugu",         "Maiduguri",      1201,
    "Enugu",         "Makurdi",        270,
    "Enugu",         "Minna",          598,
    "Enugu",         "Osogbo",         462,
    "Enugu",         "Owerri",         146,
    "Enugu",         "Port Harcourt",  229,
    "Enugu",         "Sokoto",         1272,
    "Enugu",         "Umuahia",        110,
    "Enugu",         "Uyo",            169,
    "Enugu",         "Yenagoa",        255,
    "Enugu",         "Yola",           870,
    
    "Gombe",         "Gusau",          718,
    "Gombe",         "Ibadan",         1223,
    "Gombe",         "Lagos",          1350,
    "Gombe",         "Ilorin",         1064,
    "Gombe",         "Jalingo",        279,
    "Gombe",         "Jos",            286,
    "Gombe",         "Kaduna",         566,
    "Gombe",         "Kano",           457,
    "Gombe",         "Katsina",        675,
    "Gombe",         "Lafia",          482,
    "Gombe",         "Lokoja",         750,
    "Gombe",         "Maiduguri",      400,
    "Gombe",         "Makurdi",        623,
    "Gombe",         "Minna",          745,
    "Gombe",         "Osogbo",         1383,
    "Gombe",         "Owerri",         1030,
    "Gombe",         "Port Harcourt",  1122,
    "Gombe",         "Sokoto",         931,
    "Gombe",         "Umuahia",        1010,
    "Gombe",         "Uyo",            1924,
    "Gombe",         "Yenagoa",        1145,
    "Gombe",         "Yola",           262,
    
    "Gusau",         "Ibadan",         1017,
    "Gusau",         "Lagos",          1150,
    "Gusau",         "Ilorin",         857,
    "Gusau",         "Jalingo",        1002,
    "Gusau",         "Jos",            330,
    "Gusau",         "Kaduna",         200,
    "Gusau",         "Kano",           260,
    "Gusau",         "Katsina",        463,
    "Gusau",         "Lafia",          650,
    "Gusau",         "Lokoja",         692,
    "Gusau",         "Maiduguri",      914,
    "Gusau",         "Makurdi",        774,
    "Gusau",         "Minna",          558,
    "Gusau",         "Osogbo",         972,
    "Gusau",         "Owerri",         1100,
    "Gusau",         "Port Harcourt",  1200,
    "Gusau",         "Sokoto",         274,
    "Gusau",         "Umuahia",        1150,
    "Gusau",         "Uyo",            1240,
    "Gusau",         "Yenagoa",        1270,
    "Gusau",         "Yola",           971,
    
    "Ibadan",        "Lagos",          132,
    "Ibadan",        "Ilorin",         157,
    "Ibadan",        "Jalingo",        1117,
    "Ibadan",        "Jos",            528,
    "Ibadan",        "Kaduna",         756,
    "Ibadan",        "Kano",           1005,
    "Ibadan",        "Katsina",        1065,
    "Ibadan",        "Lafia",          825,
    "Ibadan",        "Lokoja",         564,
    "Ibadan",        "Maiduguri",      1532,
    "Ibadan",        "Makurdi",        920,
    "Ibadan",        "Minna",          592,
    "Ibadan",        "Osogbo",         90,
    "Ibadan",        "Owerri",         450,
    "Ibadan",        "Port Harcourt",  656,
    "Ibadan",        "Sokoto",         890,
    "Ibadan",        "Umuahia",        580,
    "Ibadan",        "Uyo",            670,
    "Ibadan",        "Yenagoa",        510,
    "Ibadan",        "Yola",           1543,
    
    "Lagos",         "Ilorin",         291,
    "Lagos",         "Jalingo",        1264,
    "Lagos",         "Jos",            1169,
    "Lagos",         "Kaduna",         880,
    "Lagos",         "Kano",           1139,
    "Lagos",         "Katsina",        1211,
    "Lagos",         "Lafia",          941,
    "Lagos",         "Lokoja",         531,
    "Lagos",         "Maiduguri",      1665,
    "Lagos",         "Makurdi",        820,
    "Lagos",         "Minna",          725,
    "Lagos",         "Osogbo",         237,
    "Lagos",         "Owerri",         564,
    "Lagos",         "Port Harcourt",  620,
    "Lagos",         "Sokoto",         1023,
    "Lagos",         "Umuahia",        900,
    "Lagos",         "Uyo",            689,
    "Lagos",         "Yenagoa",        537,
    "Lagos",         "Yola",           1312,
    
    "Ilorin",        "Jalingo",        959,
    "Ilorin",        "Jos",            776,
    "Ilorin",        "Kaduna",         597,
    "Ilorin",        "Kano",           846,
    "Ilorin",        "Katsina",        907,
    "Ilorin",        "Lafia",          850,
    "Ilorin",        "Lokoja",         319,
    "Ilorin",        "Maiduguri",      1372,
    "Ilorin",        "Makurdi",        863,
    "Ilorin",        "Minna",          432,
    "Ilorin",        "Osogbo",         145,
    "Ilorin",        "Owerri",         667,
    "Ilorin",        "Port Harcourt",  843,
    "Ilorin",        "Sokoto",         730,
    "Ilorin",        "Umuahia",        770,
    "Ilorin",        "Uyo",            865,
    "Ilorin",        "Yenagoa",        609,
    "Ilorin",        "Yola",           319,
    
    "Jalingo",       "Jos",            542,
    "Jalingo",       "Kaduna",         822,
    "Jalingo",       "Kano",           731,
    "Jalingo",       "Katsina",        1004,
    "Jalingo",       "Lafia",          450,
    "Jalingo",       "Lokoja",         643,
    "Jalingo",       "Maiduguri",      415,
    "Jalingo",       "Makurdi",        359,
    "Jalingo",       "Minna",          608,
    "Jalingo",       "Osogbo",         1073,
    "Jalingo",       "Owerri",         808,
    "Jalingo",       "Port Harcourt",  603,
    "Jalingo",       "Sokoto",         1186,
    "Jalingo",       "Umuahia",        756,
    "Jalingo",       "Uyo",            674,
    "Jalingo",       "Yenagoa",        924,
    "Jalingo",       "Yola",           124,
    
    "Jos",           "Kaduna",         278,
    "Jos",           "Kano",           418,
    "Jos",           "Katsina",        592,
    "Jos",           "Lafia",          190,
    "Jos",           "Lokoja",         469,
    "Jos",           "Maiduguri",      592,
    "Jos",           "Makurdi",        335,
    "Jos",           "Minna",          457,
    "Jos",           "Osogbo",         776,
    "Jos",           "Owerri",         745,
    "Jos",           "Port Harcourt",  840,
    "Jos",           "Sokoto",         644,
    "Jos",           "Umuahia",        727,
    "Jos",           "Uyo",            811,
    "Jos",           "Yenagoa",        651,
    "Jos",           "Yola",           540,
    
    "Kaduna",        "Kano",           220,
    "Kaduna",        "Katsina",        428,
    "Kaduna",        "Lafia",          474,
    "Kaduna",        "Lokoja",         502,
    "Kaduna",        "Maiduguri",      874,
    "Kaduna",        "Makurdi",        500,
    "Kaduna",        "Minna",          297,
    "Kaduna",        "Osogbo",         715,
    "Kaduna",        "Owerri",         910,
    "Kaduna",        "Port Harcourt",  1003,
    "Kaduna",        "Sokoto",         400,
    "Kaduna",        "Umuahia",        890,
    "Kaduna",        "Uyo",            975,
    "Kaduna",        "Yenagoa",        1026,
    "Kaduna",        "Yola",           320,
    
    "Kano",          "Katsina",        172,
    "Kano",          "Lafia",          618,
    "Kano",          "Lokoja",         766,
    "Kano",          "Maiduguri",      574,
    "Kano",          "Makurdi",        755,
    "Kano",          "Minna",          503,
    "Kano",          "Osogbo",         915,
    "Kano",          "Owerri",         1173,
    "Kano",          "Port Harcourt",  1270,
    "Kano",          "Sokoto",         545,
    "Kano",          "Umuahia",        1153,
    "Kano",          "Uyo",            1237,
    "Kano",          "Yenagoa",        1289,
    "Kano",          "Yola",           714,
    
    "Katsina",       "Lafia",          788,
    "Katsina",       "Lokoja",         918,
    "Katsina",       "Maiduguri",      794,
    "Katsina",       "Makurdi",        860,
    "Katsina",       "Minna",          606,
    "Katsina",       "Osogbo",         1008,
    "Katsina",       "Owerri",         1142,
    "Katsina",       "Port Harcourt",  1430,
    "Katsina",       "Sokoto",         390,
    "Katsina",       "Umuahia",        1322,
    "Katsina",       "Uyo",            1406,
    "Katsina",       "Yenagoa",        1258,
    "Katsina",       "Yola",           875,
    
    "Lafia",         "Lokoja",         788,
    "Lafia",         "Maiduguri",      788,
    "Lafia",         "Makurdi",        82,
    "Lafia",         "Minna",          297,
    "Lafia",         "Osogbo",         287,
    "Lafia",         "Owerri",         490,
    "Lafia",         "Port Harcourt",  997,
    "Lafia",         "Sokoto",         840,
    "Lafia",         "Umuahia",        456,
    "Lafia",         "Uyo",            555,
    "Lafia",         "Yenagoa",        606,
    "Lafia",         "Yola",           736,
    
    "Lokoja",        "Maiduguri",      1063,
    "Lokoja",        "Makurdi",        342,
    "Lokoja",        "Minna",          309,
    "Lokoja",        "Osogbo",         305,
    "Lokoja",        "Owerri",         424,
    "Lokoja",        "Port Harcourt",  521,
    "Lokoja",        "Sokoto",         985,
    "Lokoja",        "Umuahia",        405,
    "Lokoja",        "Uyo",            490,
    "Lokoja",        "Yenagoa",        540,
    "Lokoja",        "Yola",           945,
    
    "Maiduguri",     "Makurdi",        930,
    "Maiduguri",     "Minna",          1052,
    "Maiduguri",     "Osogbo",         1372,
    "Maiduguri",     "Owerri",         1142,
    "Maiduguri",     "Port Harcourt",  1419,
    "Maiduguri",     "Sokoto",         1123,
    "Maiduguri",     "Umuahia",        1323,
    "Maiduguri",     "Uyo",            1405,
    "Maiduguri",     "Yenagoa",        1253,
    "Maiduguri",     "Yola",           430,
    
    "Makurdi",       "Minna",          440,
    "Makurdi",       "Osogbo",         618,
    "Makurdi",       "Owerri",         400,
    "Makurdi",       "Port Harcourt",  505,
    "Makurdi",       "Sokoto",         1116,
    "Makurdi",       "Umuahia",        374,
    "Makurdi",       "Uyo",            473,
    "Makurdi",       "Yenagoa",        524,
    "Makurdi",       "Yola",           674,
    
    "Minna",         "Osogbo",         552,
    "Minna",         "Owerri",         735,
    "Minna",         "Port Harcourt",  830,
    "Minna",         "Sokoto",         674,
    "Minna",         "Umuahia",        716,
    "Minna",         "Uyo",            800,
    "Minna",         "Yenagoa",        254,
    "Minna",         "Yola",           1124,
    
    "Osogbo",        "Owerri",         495,
    "Osogbo",        "Port Harcourt",  623,
    "Osogbo",        "Sokoto",         348,
    "Osogbo",        "Umuahia",        564,
    "Osogbo",        "Uyo",            645,
    "Osogbo",        "Yenagoa",        469,
    "Osogbo",        "Yola",           225,
    
    "Owerri",        "Port Harcourt",  112,
    "Owerri",        "Sokoto",         1411,
    "Owerri",        "Umuahia",        165,
    "Owerri",        "Uyo",            250,
    "Owerri",        "Yenagoa",        115,
    "Owerri",        "Yola",           1008,
    
    "Port Harcourt", "Sokoto",         1203,
    "Port Harcourt", "Umuahia",        114,
    "Port Harcourt", "Uyo",            120,
    "Port Harcourt", "Yenagoa",        104,
    "Port Harcourt", "Yola",           1105,
    
    "Sokoto",        "Umuahia",        1376,
    "Sokoto",        "Uyo",            1475,
    "Sokoto",        "Yenagoa",        1527,
    "Sokoto",        "Yola",           1187,
    
    "Umuahia",       "Uyo",            88,
    "Umuahia",       "Yenagoa",        281,
    "Umuahia",       "Yola",           917,
    
    "Uyo",           "Yenagoa",        234,
    "Uyo",           "Yola",           1073,
    
    "Yenagoa",       "Yola",           1124
  )
  
  cities <- unique(c(city_dist$from, city_dist$to))
  n <- length(cities)
  city_mat <- matrix(0, n, n, dimnames = list(cities, cities))
  
  for (i in seq_len(nrow(city_dist))) {
    city_mat[city_dist$from[i], city_dist$to[i]] <- city_dist$km[i]
    city_mat[city_dist$to[i], city_dist$from[i]] <- city_dist$km[i]
  }
  
  ngdist <- as.dist(city_mat)
  usethis::use_data(ngdist, overwrite = .__rda_exists(ngdist))
})
