# Source file: fixregions-utils.R
#
# GPL-3 License
#
# Copyright (C) 2019-2026 Victor Ordu.

.fix_region_automatic <- function(regions_object, region_table)
{
  stopifnot(is.object(regions_object))
  region_table <- unclass(region_table)
  ## Internal function to enable identification of entries that need to
  ## be fixed and preparing attributes that will enable further processing
  ## downstream.
  cant.fix <- fix.status <- character()
  get_proper_value <- function(str, regions) {
    abbrFCT <- .toggle_fct_format("abbrev")
    if (!is.na(match(str, regions))) {
      return(str)
    } 
    if (inherits(regions, "states")) {
      if ( agrepl(str, abbrFCT, max.distance = .pkgLevDistance()) &&
          identical(toupper(str), abbrFCT)) {
        return(abbrFCT) 
      }
    }
    str <- .trim_whitespace(str)
    ## Now, check for exact matching.
    rgx <- paste0('^', str, '$')
    good <- unique(grep(rgx, regions, value = TRUE, ignore.case = TRUE))
    if (length(good) == 1L) { 
      return(good)
    }
    ## Otherwise check for approximate matches.
    fixed <- agrep(str, regions, value = TRUE, max.distance = .pkgLevDistance())
    if (length(fixed) == 1L) {
      fs <- c(fix.status, fixed)
      names(fs) <- c(names(fix.status), str)
      fix.status <<- fs
      return(fixed)
    }
    if (length(fixed) > 1L) {
      multimatch <- paste(fixed, collapse = ", ")
      cli::cli_inform(
        "'{str}' approximately matched more than one region - {multimatch}"
      )
    }
    # if we get to this point, return the misspelt region unchanged
    cant.fix <<- c(cant.fix, str)
    str
  }
  spellchecked <- vapply(
    regions_object,
    get_proper_value,
    character(1),
    regions = region_table,
    USE.NAMES = FALSE
  )
  ## Reduce data for reporting on fixes to only unique instances 
  if (length(fix.status) > 1L) {
    allfixes <- names(fix.status)
    if (anyDuplicated(allfixes)) {
      duplicates <- which(duplicated(allfixes))
      fix.status <- fix.status[-duplicates]
    }
  }
  attr(spellchecked, "regions.fixed") <- fix.status
  attr(spellchecked, "misspelt") <- sort(unique(cant.fix))
  structure(spellchecked, class = class(regions_object))
}




.trim_whitespace <- function(x)
{
  ## First remove spaces around slashes and hyphens
  # str <- gsub("\\s\\/", "/", str)
  # str <- gsub("\\/\\s", "/", str)
  # str <- sub("-\\s", "-", str)
  # sub("^Egbado/", "", str) ## TODO: Address hard-coding
  x
}




# Tells the user about what repairs have been made to the spellings
# @param obj - the checked object, which has attributes with relevant details
# @param usedialog Whether to display a dialog (on Windows only).
.report_on_fixes <- function(obj, usedialog = FALSE)
{
  spell.details <- attributes(obj)
  badspell <- spell.details$misspelt
  hasBadspell <- !identical(badspell, character(0))
  msg.bad <- msg.good <- ""
  if (hasBadspell) {
    hdr.bad <- .messageHeader("Fix(es) not applied")
    nofix.bullets <-
      vapply(badspell, function(x) paste("*", x), character(1))
    msg.bad <- paste0(hdr.bad, paste(nofix.bullets, collapse = "\n"))
  }
  # Put the message together
  fixes <- spell.details$regions.fixed
  if (!identical(fixes, character(0))) {
    hdr.good <- .messageHeader("Successful fix(es)")
    fixed.bullets <-
      mapply(function(a, z) {
        sprintf("* %s => %s", a, z)
      }, 
      names(fixes), fixes)
    msg.good <- paste0(hdr.good, paste(fixed.bullets, collapse = "\n"))
    if (hasBadspell)
      msg.good <- paste0(msg.good, "\n")    # just add newline
  }
  if (!nchar(msg.good) && !nchar(msg.bad)) {
    return()
  }
  final.msg <- paste(msg.good, msg.bad, sep = "\n")
  if (usedialog) {
    utils::winDialog("ok", final.msg)
  }
  else {
    cli::cli_alert_info(final.msg)
  }
}




.messageHeader <- function(hdr)
{
  stopifnot(is.character(hdr))
  hdr <- paste0(hdr, ":")
  dashes <- strrep("-", nchar(hdr))
  hdr <- paste(hdr, dashes, sep = '\n')
  paste0(hdr, "\n")
}




## Interactively fixes regions that are bad - this function is primarily
## used for repairing LGA names, since they are so many.
## @param lgas.object The vector of LGA names that is being repaired. This vector
## is generated by `.fix_region_automatic` and has an attribute called
## `misspelt`, which is the collection of names needing repair.
## @param usedialog Whether to use dialog in prompts (only on Windows)
.fix_lgas_interactive <- function(lgas.object, usedialog = FALSE)
{
  stopifnot(exprs = {
    is.atomic(lgas.object)
    length(attributes(lgas.object)) > 1L
    is.logical(usedialog)
  })
  skipped <- character()   # instead of NULL, for validation downstream
  for (bad in attr(lgas.object, "misspelt")) {
    result <- .attempt_lga_fix(bad, usedialog)
    if (is.null(result)) {
      return()
    }
    if (identical(result, character())) {    # QUIT
      break
    }
    if (identical(result, bad)) {            # SKIP
      skipped <- c(skipped, bad)
      next
    }
    lgas.object <- .update_attributes(bad, result, lgas.object)
  }
  .suggest_manual_fix(skipped, usedialog)
  lgas.object
}




.attempt_lga_fix <- function(bad, usedialog) {
  allLgas <- lgas()
  specialopts <- list(retry = "RETRY", skip = "SKIP", quit = "QUIT")
  msg.fixWhich <- paste("Fixing", sQuote(bad))
  repeat {
    prompt <- paste(msg.fixWhich, "Enter a search term: ", sep = ' - ')
    pattern <- .collect_searchterm(prompt, usedialog) 
    if (pattern == "" || is.null(pattern)) {
      return(NULL)
    }
    matched <- sort(grep(pattern, allLgas, value = TRUE, ignore.case = TRUE))
    choices <- c(matched, unlist(unname(specialopts)))
    menuopt <- utils::menu(choices, graphics = usedialog, "Select the LGA")
    chosen <- choices[menuopt]
    if (chosen == specialopts$retry) {
      next
    }
    break
  }
  if (chosen == specialopts$quit) {
    return(character())
  }
  if (chosen == specialopts$skip) {
    return(bad)
  }
  chosen
}




# Updates the attributes added to an lgas object in the course of attempting
# to fix spelling mistakes. This attributes are required internally for
# assessing the status of the fixes applied and for reporting to the user
.update_attributes <- function(misspelled, repaired, obj) {
  stopifnot(exprs = {
    rlang::is_string(misspelled)
    rlang::is_string(repaired)
  })
  obj <- sub(misspelled, repaired, obj, fixed = TRUE)
  attr.misspelt <- attr(obj, "misspelt")
  attr(obj, "misspelt") <- attr.misspelt[attr.misspelt != misspelled]
  attr.fixed <- c(attr(obj, "regions.fixed"), repaired)
  names(attr.fixed) <- c(names(attr.fixed), misspelled)
  attr(obj, "regions.fixed") <- attr.fixed
  obj
}




.suggest_manual_fix <- function(skipped, useWinDialog) {
  stopifnot(exprs = {
    is.character(skipped)
    is.logical(useWinDialog)
  })
  if (length(skipped)) {
    msg <- paste0(
      "The following items were skipped: ",
      paste(skipped, collapse = ", "),
      ". Consider using 'fix_region_manual'"
    )
    if (useWinDialog) {
      utils::winDialog("ok", msg)
    }
    else {
      cli::cli_inform(msg)
    }
  }
}




.collect_searchterm <- function(prompt, useWinDialog) {
  result <- if (useWinDialog) {
    utils::winDialogString(prompt, "")
  }
  else {
    readline(prompt)
  }
  result
}




.assert_region <- function(x) {
  if (!is_state(x) && !is_lga(x)) {
    cli::cli_abort("{sQuote(x, q = FALSE)} is not a valid region")
  }
  x
}




.strip_temp_attrs <- function(x)
{
  cl <- class(x)
  attributes(x) <- NULL
  structure(x, class = cl)
}
